name: "Setup Docker Environment"
description: "Reusable steps for setting up QEMU, Docker Buildx, AWS ECR login, Supersetbot, and optionally Docker Compose"
inputs:
  build:
    description: "Used for building?"
    required: false
    default: "false"
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: false
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: false
  aws-region:
    description: "AWS Region"
    required: false
    default: "us-west-2"
  install-docker-compose:
    description: "Flag to install Docker Compose"
    required: false
    default: "true"

outputs: {}
runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      if: ${{ inputs.build == 'true' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: ${{ inputs.build == 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Install Docker Compose
      if: ${{ inputs.install-docker-compose == 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings

        # Download and save the Docker GPG key in the correct format
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

        # Ensure the key file is readable
        sudo chmod a+r /etc/apt/keyrings/docker.gpg

        # Add the Docker repository using the correct key
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Update package lists and install Docker Compose plugin
        sudo apt update
        sudo apt install -y docker-compose-plugin

    - name: Docker Version Info
      shell: bash
      run: docker info
